import Test from "./Test";

export const Grade2 = {
  chapters: [
    {
      navigation: "Chapter1", // you need to specify name or key when calling navigate
      title: "Раздел 1",
      name: "Я-исследователь",
      icon: require("../../../assets/explore.png"),
      colorOne: "darkorange",
      colorTwo: "goldenrod",
      key: "C1",
      component: Test,
    },
    {
      navigation: "Chapter2",
      title: "Раздел 2",
      name: "Живая природа",
      icon: require("../../../assets/butterfly.png"),
      colorOne: "darkolivegreen",
      colorTwo: "darkgreen",
      key: "C2",
      component: Test,
    },
    {
      navigation: "Chapter3",
      title: "Раздел 3",
      name: "Вещества и их свойства",
      icon: require("../../../assets/water-cycle.png"),
      colorOne: "tomato",
      colorTwo: "firebrick",
      key: "C3",
      component: Test,
    },
    {
      navigation: "Chapter4",
      title: "Раздел 4",
      name: "Природные ресурсы",
      icon: require("../../../assets/soil.png"),
      colorOne: "sandybrown",
      colorTwo: "peachpuff",
      key: "C4",
      component: Test,
    },
    {
      navigation: "Chapter5",
      title: "Раздел 5",
      name: "Земля и космос",
      icon: require("../../../assets/astronaut.png"),
      colorOne: "navy",
      colorTwo: "dodgerblue",
      key: "C5",
      component: Test,
    },
    {
      navigation: "Chapter6",
      title: "Раздел 6",
      name: "Физика природы",
      icon: require("../../../assets/book.png"),
      colorOne: "mediumturquoise",
      colorTwo: "royalblue",
      key: "C6",
      component: Test,
    },
  ],
};
