import Test from "./Test";

export const Grade3 = {
  chapters: [
    {
      navigation: "Chapter1",
      title: "Раздел 1",
      name: "Растения",
      icon: require("../../../assets/watering-plants.png"),
      colorOne: "palevioletred",
      colorTwo: "pink",
      key: "C1",
      component: Test,
    },
    {
      navigation: "Chapter2",
      title: "Раздел 2",
      name: "Животные",
      icon: require("../../../assets/antelope.png"),
      colorOne: "mediumturquoise",
      colorTwo: "powderblue",
      key: "C2",
      component: Test,
    },
    {
      navigation: "Chapter3",
      title: "Раздел 3",
      name: "Человек",
      icon: require("../../../assets/brain.png"),
      colorOne: "plum",
      colorTwo: "thistle",
      key: "C3",
      component: Test,
    },
    {
      navigation: "Chapter4",
      title: "Раздел 4",
      name: "Вещества и их \nсвойства. Воздух и вода",
      icon: require("../../../assets/wind.png"),
      colorOne: "coral",
      colorTwo: "darksalmon",
      key: "C4",
      component: Test,
    },
    {
      navigation: "Chapter5",
      title: "Раздел 5",
      name: "Физика природы",
      icon: require("../../../assets/sound-wave.png"),
      colorOne: "indigo",
      colorTwo: "darkmagenta",
      key: "C5",
      component: Test,
    },
    {
      navigation: "Chapter6",
      title: "Раздел 6",
      name: "Вещества и их \nсвойства. Природные ресурсы",
      icon: require("../../../assets/log.png"),
      colorOne: "darkgreen",
      colorTwo: "darkolivegreen",
      key: "C6",
      component: Test,
    },
    {
      navigation: "Chapter7",
      title: "Раздел 7",
      name: "Земля и космос",
      icon: require("../../../assets/constellation.png"),
      colorOne: "midnightblue",
      colorTwo: "mediumblue",
      key: "C7",
      component: Test,
    },
    {
      navigation: "Chapter8",
      title: "Раздел 8",
      name: "Силы и движение",
      icon: require("../../../assets/swim-ring.png"),
      colorOne: "mediumvioletred",
      colorTwo: "hotpink",
      key: "C8",
      component: Test,
    },
  ],
};
