import Test from "./Test";

export const Grade4 = {
  chapters: [
    {
      navigation: "Chapter1",
      title: "Раздел 1",
      name: "Мир науки.",
      icon: require("../../../assets/atom.png"),
      colorOne: "chocolate",
      colorTwo: "burlywood",
      key: "C1",
      component: Test,
    },
    {
      navigation: "Chapter2",
      title: "Раздел 2",
      name: "Вселенная. Земля. Человек.",
      icon: require("../../../assets/planet.png"),
      colorOne: "darkolivegreen",
      colorTwo: "darkkhaki",
      key: "C2",
      component: Test,
    },
    {
      navigation: "Chapter3",
      title: "Раздел 3",
      name: "Вещества и материалы",
      icon: require("../../../assets/chemistry.png"),
      colorOne: "mediumorchid",
      colorTwo: "lightpink",
      key: "C3",
      component: Test,
    },
    {
      navigation: "Chapter4",
      title: "Раздел 4",
      name: "Процессы в живой и \nнеживой природе",
      icon: require("../../../assets/rock-garden.png"),
      colorOne: "seagreen",
      colorTwo: "yellowgreen",
      key: "C4",
      component: Test,
    },
    {
      navigation: "Chapter5",
      title: "Раздел 5",
      name: "Энергия и движение",
      icon: require("../../../assets/renewable-energy.png"),
      colorOne: "navy",
      colorTwo: "cornflowerblue",
      key: "C5",
      component: Test,
    },
    {
      navigation: "Chapter6",
      title: "Раздел 6",
      name: "Экология и \nустойчивое развитие",
      icon: require("../../../assets/eco-friendly.png"),
      colorOne: "purple",
      colorTwo: "indigo",
      key: "C6",
      component: Test,
    },
    {
      navigation: "Chapter7",
      title: "Раздел 7",
      name: "Открытия, меняющие мир",
      icon: require("../../../assets/discovery.png"),
      colorOne: "darkorange",
      colorTwo: "goldenrod",
      key: "C7",
      component: Test,
    },
  ],
};
