export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
export const USER_ADD_EXPERIENCE_45 = 'USER_ADD_EXPERIENCE_45';
export const USER_ADD_EXPERIENCE_90 = 'USER_ADD_EXPERIENCE_90';
export const USER_ADD_EXPERIENCE_135 = 'USER_ADD_EXPERIENCE_135';
export const USER_ADD_EXPERIENCE_180 = 'USER_ADD_EXPERIENCE_180';