export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
export const ACHIEVEMENTS_STATE_CHANGE = 'ACHIEVEMENTS_STATE_CHANGE';
export const USER_ADD_EXPERIENCE_45 = 'USER_ADD_EXPERIENCE_45';
export const USER_ADD_EXPERIENCE_90 = 'USER_ADD_EXPERIENCE_90';
export const USER_ADD_EXPERIENCE_135 = 'USER_ADD_EXPERIENCE_135';
export const USER_ADD_EXPERIENCE_180 = 'USER_ADD_EXPERIENCE_180';
export const MODAL_OPENED = "MODAL_OPENED";
export const MODAL_CLOSED = "MODAL_CLOSED";